# Header
menu:
  主页: /
  所有文章: /archives
  编程: /tags/编程
  网络: /tags/网络
  美工: /tags/美工

# SubNav
subnav:
  github: "http://itxiehui.github.io"
  #weibo: "#"
  rss: "/atom.xml"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/head.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
    廖雪峰的官方网站: http://www.liaoxuefeng.com/
    阮一峰的网络日志: http://www.ruanyifeng.com/blog/
    红茶三杯: http://ccietea.com/
    百度前端技术学院: http://ife.baidu.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 广东技术师范学院信息技术协会，一个为广大同学提供学习、实践和交流机会的平台。
